name: Deployment

on:
  push:
    branches: [ deploy ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DO_REGISTRY_TOKEN }}
    steps:
    - uses: actions/checkout@v2
      with: 
        submodules: recursive
    - name: Install doctl 
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_REGISTRY_TOKEN }}
    - name: Image
      run: docker build . -t kelson/movienight:latest
    - name: Dotctl Login
      run: doctl registry login --expiry-seconds 600
    - name: Tag image 
      run: docker tag kelson/movienight:latest registry.digitalocean.com/kelson-registry/movienight:latest
    - name: Push image to DO Container Registry 
      run: docker push registry.digitalocean.com/kelson-registry/movienight:latest
